# Generated by Django 4.2.7 on 2025-10-04 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_add_soft_delete'),
        ('collab', '0004_add_database_constraints'),
    ]

    operations = [
    ]
