# Generated by Django 4.2.30 on 2026-06-13 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collab', '0005_merge_20251003_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='essay',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='page',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
